name: Update README with Gist

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 00:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run Gist Injection Script
        run: python scripts/inject-gist.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "📈 update: inject gist to README"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
